name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Replace WEHOOK secret in index.html
      run: |
        sed -i "s/\${{ secrets.WEHOOK }}/$WEHOOK/g" index.html
      env:
        WEHOOK: ${{ secrets.WEHOOK }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # Adjust based on where index.html is located
